---
- hosts: test_server
  become: true
  tasks:
    - name: Install Package
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache Server
      service:
        name: httpd
        state: started
        enabled: true
    - name: Deploy Static Website
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Allow http/https
      command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https
    - name: Bounce firewalld
      service: name=firewalld state=restarted
...
